In [ ]:
#RESHAPING AN ARRAY FROM 1D TO 2D
import numpy as np

# Example 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2D array with 2 rows and 3 columns
arr_2d = arr_1d.reshape(2, 3)

print("1D Array:")
print(arr_1d)

print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5 6]

2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# TO CREATE A LOWER TRIANGULAR MATRIX WITH ONES (tri)
# Full Triangular Matrix (tri)
import numpy as np

n = 4  # Size of the matrix
tri_matrix = np.tri(n)

print("Full Triangular Matrix (Lower):")
print(tri_matrix)

Full Triangular Matrix (Lower):
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [ ]:
# TO CREATE A LOWER TRIANGULAR MATRIX WITH ONES (tri-u)
import numpy as np

# Create a sample 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extract the upper triangular part
upper_tri_matrix = np.triu(matrix)

print("Upper Triangular Matrix:")
print(upper_tri_matrix)

Upper Triangular Matrix:
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [ ]:
# TO CREATE A LOWER TRIANGULAR MATRIX WITH ONES (tri-l)
import numpy as np

# Create a sample 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extract the lower triangular part
lower_tri_matrix = np.tril(matrix)

print("Lower Triangular Matrix:")
print(lower_tri_matrix)

Lower Triangular Matrix:
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
import numpy as np

# Creating a matrix using np.mat()
A = np.mat('1 2 3; 4 5 6; 7 8 9')

# Display the matrix
print("Matrix A:")
print(A)

# Transpose of the matrix
print("\nTranspose of A:")
print(A.T)

# Matrix multiplication
B = np.mat('9 8 7; 6 5 4; 3 2 1')
print("\nMatrix B:")
print(B)

C = A * B  # Matrix multiplication using np.mat()
print("\nMatrix Multiplication (A * B):")
print(C)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Multiplication (A * B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
# Define a sample list
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

# Basic slicing: list[start:stop:step]
print(numbers[2:6])     # Output: [30, 40, 50, 60] (index 2 to 5)
print(numbers[:4])      # Output: [10, 20, 30, 40] (from start to index 3)
print(numbers[5:])      # Output: [60, 70, 80, 90, 100] (index 5 to end)
print(numbers[::2])     # Output: [10, 30, 50, 70, 90] (every 2nd element)
print(numbers[::-1])    # Output: [100, 90, 80, 70, 60, 50, 40, 30, 20, 10] (reversed list)

# Slicing a string
text = "Hello, World!"
print(text[0:5])   # Output: 'Hello'
print(text[::-1])  # Output: '!dlroW ,olleH' (reversed string)


[30, 40, 50, 60]
[10, 20, 30, 40]
[60, 70, 80, 90, 100]
[10, 30, 50, 70, 90]
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]
Hello
!dlroW ,olleH


In [ ]:
# Indexing in a list
numbers = [10, 20, 30, 40, 50]

print(numbers[0])  # Output: 10 (first element)
print(numbers[2])  # Output: 30 (third element)
print(numbers[-1]) # Output: 50 (last element)
print(numbers[-3]) # Output: 30 (third element from the end)

# Indexing in a string
text = "Python"

print(text[0])   # Output: 'P' (first character)
print(text[3])   # Output: 'h' (fourth character)
print(text[-1])  # Output: 'n' (last character)
print(text[-4])  # Output: 't' (fourth character from the end)


10
30
50
30
P
h
n
t


In [ ]:
import numpy as np

# Create an original NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a copy using np.copy()
copied_array = np.copy(original_array)

# Modify the copied array
copied_array[0] = 99

# Print both arrays to see the difference
print("Original Array:", original_array)  # Output: [1 2 3 4 5]
print("Copied Array:", copied_array)      # Output: [99  2  3  4  5]


Original Array: [1 2 3 4 5]
Copied Array: [99  2  3  4  5]


In [ ]:
# Finding the maximum value in a list
numbers = [10, 25, 5, 40, 15]
print("Maximum value:", max(numbers))  # Output: 40

# Finding the maximum value in a tuple
values = (8, 3, 12, 1, 7)
print("Maximum value:", max(values))  # Output: 12

# Finding the maximum character in a string (based on ASCII value)
text = "hello"
print("Maximum character:", max(text))  # Output: 'o' (highest ASCII value)

# Finding the maximum among multiple numbers
print("Maximum of (10, 20, 30):", max(10, 20, 30))  # Output: 30

# Using max() with a key function
words = ["apple", "banana", "kiwi", "grape"]
print("Longest word:", max(words, key=len))  # Output: 'banana' (longest length)


Maximum value: 40
Maximum value: 12
Maximum character: o
Maximum of (10, 20, 30): 30
Longest word: banana


In [ ]:
# Finding the minimum value in a list
numbers = [10, 25, 5, 40, 15]
print("Minimum value:", min(numbers))  # Output: 5

# Finding the minimum value in a tuple
values = (8, 3, 12, 1, 7)
print("Minimum value:", min(values))  # Output: 1

# Finding the minimum character in a string (based on ASCII value)
text = "hello"
print("Minimum character:", min(text))  # Output: 'e' (smallest ASCII value)

# Finding the minimum among multiple numbers
print("Minimum of (10, 20, 30):", min(10, 20, 30))  # Output: 10

# Using min() with a key function
words = ["apple", "banana", "kiwi", "grape"]
print("Shortest word:", min(words, key=len))  # Output: 'kiwi' (shortest length)


Minimum value: 5
Minimum value: 1
Minimum character: e
Minimum of (10, 20, 30): 10
Shortest word: kiwi


In [ ]:
# Summing elements in a list
numbers = [10, 20, 30, 40, 50]
print("Sum of numbers:", sum(numbers))  # Output: 150

# Summing elements in a tuple
values = (5, 15, 25, 35)
print("Sum of values:", sum(values))  # Output: 80

# Using sum() with a start value
more_numbers = [1, 2, 3]
print("Sum with start value 10:", sum(more_numbers, 10))  # Output: 16

# Summing elements of a NumPy array
import numpy as np
array = np.array([4, 8, 12])
print("Sum of NumPy array:", sum(array))  # Output: 24

# Summing elements of a dictionary (keys by default)
my_dict = {1: "a", 2: "b", 3: "c"}
print("Sum of dictionary keys:", sum(my_dict))  # Output: 6


Sum of numbers: 150
Sum of values: 80
Sum with start value 10: 16
Sum of NumPy array: 24
Sum of dictionary keys: 6
